module.exports =
{
    CONTENT:
    {
        CATEGORIES_INFO:
        [
            {
                english_title: 'EXISTENTIAL NOTIONS',
                spanish_title: 'NOCIONES EXISTENCIALES',
                german_title: 'existenzielle Begriffe',
                french_title: 'notions existentielles',
                italian_title: 'Nozioni esistenziali',
                english_sub:    ['Existence, inexistence',      'Presence, absence',        'General quality',      'Event',            'Certainty, uncertainty'],
                spanish_sub:    ['Existencia, inexistencia',    'Presencia, ausencia',      'Cualidad general',     'Acontecimiento',   'Certeza, incertidumbre'],
                german_sub:     ['Existenz, Nichtexistenz',     'Anwesenheit, Abwesenheit', 'Allgemeine Qualität',  'Veranstaltung',    'Sicherheit, Unsicherheit'],
                french_sub:     ['Existencia, inexistencia',    'Présence absence',         'Qualité générale',     'événement',        'Certitude, incertitude'],
                italian_sub:    ['Esistenza, inesistenza',      'Presenza, assenza',        'Qualità generale',     'Avvenimento',      'Certezza, incertezza']
            },
            {
                english_title: 'QUANTITATIVE',
                spanish_title: 'NOCIONES CUANTITATIVAS',
                german_title: 'quantitativ',
                french_title: 'QUANTITATIVE',
                italian_title: 'NOZIONI QUANTITATIVE',
                english_sub:    ['Numerical quantity', 'Cardinal numbers',     'Ordinal numbers',      'Relative quantity',    'Degree',],//'height','size','distance','speed','weight','area','temperature',],
                spanish_sub:    ['Cantidad numérica',  'Números cardinales',   'Números ordinales',    'Cantidad relativa',    'Grado'],
                german_sub:     ['Numerische Menge',    'Kardinalzahlen',       'Ordnungszahlen',       'Relative Menge',       'Grad'],
                french_sub:     ['Quantité numérique',  'nombres cardinaux',    'Nombres ordinaux',     'Quantité relative',    'Degré'],
                italian_sub:    ['Quantità numerica',  'Numeri cardinali',   'Numeri ordinali',    'Quantità relativa',     'Grado']
            },
        ],
        EXISTENTIAL_NOTIONS:
        [
            {
                english_title: 'Existence, lack of existence',
                spanish_title: 'Existencia, inexistencia',
                german_title: 'Existenz, Nichtexistenz',
                french_title: 'Existencia, inexistencia',
                italian_title: 'Esistenza, inesistenza',
                english_word: ['there is (not) / there are (not)','to have got','to live'],
                spanish_word: ['(no) haber','tener','vivir'],
                german_word: ['(kein […]) geben','haben','leben'],
                french_word: ['(ne pas) avoir','avoir','vivre'],
                italian_word: ['(non) esserci','avere','vivere'],
                english_phrase: ['There are many museums in Madrid. ','My house hasn\'t got a terrace.','I live in Switzerland. '],
                spanish_phrase: ['En Madrid hay muchos museos','Mi casa no tiene terraza.','Vivo en Suiza.'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['A Madrid ci sono molti musei.','La mia casa non ha il terrazzo.','Vivo a Barcellona.']
            },
            {
                english_title: 'Presence, absence',
                spanish_title: 'Presencia, ausencia',
                german_title: 'Anwesenheit, Abwesenheit',
                french_title: 'Présence absence',
                italian_title: 'Presenza, assenza',
                english_word: [' there is / thre are','(not) to be','without','with'],
                spanish_word: ['haber','(no) estar','sin','con'],
                german_word: ['','(nicht) sein, (sich) befinden','ohne','mit'],
                french_word: ['avoir','(ne pas) être','sans','avec'],
                italian_word: ['esserci','(non) essere','senza','con'],
                english_phrase: ['There are many students in the class.','Peter is at home. ','I like coffee without sugar.','I drink tea with milk.'],
                spanish_phrase: ['Hay muchos alumnos en clase.','Pedro está en casa.','Me gusta el café sin azúcar.','Bebo té con leche.'],
                german_phrase: ['','','',''],
                french_phrase: ['','','',''],
                italian_phrase: ['Ci sono molti alunni in classe.','Pietro è a casa.','Mi piace il caffè senza zucchero.','Bevo tè con latte.']
            },
            {
                english_title: 'General quality',
                spanish_title: 'Cualidad general',
                german_title: 'Allgemeine Qualität',
                french_title: 'Qualité générale',
                italian_title: 'Qualità generale',
                english_word: ['to be'],
                spanish_word: ['ser'],
                german_word: ['sein'],
                french_word: ['être'],
                italian_word: ['essere'],
                english_phrase: ['The Spanish lesson is funny.'],
                spanish_phrase: ['La clase de español es divertida.'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['La lezione di spagnolo è divertente.']
            },
            {
                english_title: 'Event',
                spanish_title: 'Acontecimiento',
                german_title: 'Veranstaltung',
                french_title: 'événement',
                italian_title: 'Avvenimento',
                english_word: ['to be'],
                spanish_word: ['ser'],
                german_word: ['sein, stattfinden'],
                french_word: ['avoir lieu'],
                italian_word: ['essere'],
                english_phrase: ['The party is tomorrow.'],
                spanish_phrase: ['La fiesta es mañana.'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['La festa è domani.']
            },
            {
                english_title: 'Certainty, uncertainty',
                spanish_title: 'Certeza, incertidumbre',
                german_title: 'Sicherheit, Unsicherheit',
                french_title: 'Certitude, incertitude',
                italian_title: 'Certezza, incertezza',
                english_word: ['maybe','perhaps/maybe'],
                spanish_word: ['ser possbile','quizá(s)'],
                german_word: ['möglich sein','vielleicht'],
                french_word: ['être possible','peut-être'],
                italian_word: ['essere possibile','quizá(s)'],
                english_phrase: ['Are you coming to the cinema? Maybe. ','Are you going out tonight? Perhaps. '],
                spanish_phrase: ['Vienes al cine? Es posible. ','Sales esta noche? Quizás. '],
                german_phrase: ['',''],
                french_phrase: ['',''],
                italian_phrase: ['Vieni al cinema? È possibile.','Esci questa sera? Forse.']
            },
        ],
        QUANTITATIVE:
        [
            {
                english_title: 'Numerical quantity',
                spanish_title: 'Cantidad numérica',
                german_title: 'Numerische Menge',
                french_title: 'Quantité numérique',
                italian_title: 'Quantità numerica',
                english_word:['number'],
                spanish_word:['numero'],
                german_word:['Zahl'],
                french_word:['nombre'],
                italian_word:['numero'],
                english_phrase: ['They learn the numbers from 1 to 10'],
                spanish_phrase: ['Aprenden los números del 1 al 10.'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['Imparano i numeri da 1 a 10.']
            },
            {
                english_title: 'Cardinal numbers',
                spanish_title: 'Números cardinales',
                german_title: 'Kardinalzahlen',
                french_title: 'nombres cardinaux',
                italian_title: 'Numeri cardinali',
                english_word:['one','two','three','four'],
                spanish_word:['uno','dos','tres','cuatro'],
                german_word:['eins','zwei','drei','vier'],
                french_word:['un','deux','trois','quatre'],
                italian_word:['uno','due','tre','quattro'],
                english_phrase: ['How many pencils do you want to buy? One.','I have two brothers.','My father has three children.','My house has four rooms.'],
                spanish_phrase: ['Cuántos lápices compras? Uno.','Tengo dos hermanos.','Mi padre tiene tres hijos.','Mi casa tiene cuatro habitaciones.'],
                german_phrase: ['','','',''],
                french_phrase: ['','','',''],
                italian_phrase: ['Quante matite compri? Una.','Ho due fratelli','Mio padre ha tre figli.','La mia casa ha quattro stanze.']
            },
            {
                english_title: 'Ordinal numbers',
                spanish_title: 'Números ordinales',
                german_title: 'Ordinalzahlen',
                french_title: 'Nombres ordinaux',
                italian_title: 'Numeri ordinali',
                english_word:['first','second','third'],
                spanish_word:['primero','segundo','tercero'],
                german_word:['Erstens, erster, erste, erstes','zweiter, zweite, zweites','dritter, dritte'],
                french_word:['premier','deuxième','troisième'],
                italian_word:['primo','secondo','terzo'],
                english_phrase: ['Which floor do you live in? In the first floor.','Her house is in the second street.','He is the third of the list. '],
                spanish_phrase: ['En qué piso vives? En el primero.','Su casa está en la segunda calle.','Está el tercero en la lista.'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['A che piano vivi? Al primo','La sua casa si trova nella seconda strada.','È il terzo della lista.']
            },
            {
                english_title: 'Relative quantity',
                spanish_title: 'Cantidad relativa',
                german_title: 'Relative Menge',
                french_title: 'Quantité relative',
                italian_title: 'Quantità relativa',
                english_word:['people','price','more'],
                spanish_word:['gente','precio','más'],
                german_word:['Menschen','Preis','mehr'],
                french_word:['gens','prix','plus'],
                italian_word:['gente','prezzo','più'],
                english_phrase: ['There are many people in the museum','How much is this handbag? I can\'t see the price.','Would you like more coffee?'],
                spanish_phrase: ['Hay mucha gente en el museo.','Qué precio tiene este bolso? ','Quieres más café?'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['C\'è molta gente nel museo.','Che prezzo ha questa borsa?',' Mi piace con più latte.'],
            },
            {
                english_title: 'Degree',
                spanish_title: 'Grado',
                german_title: 'Grad',
                french_title: 'Degré',
                italian_title: 'Grado',
                english_word:['very','much more','less'],
                spanish_word:['muy','más','menos'],
                german_word:['sehr','mehr, lieber','wenig '],
                french_word:['très','plus','moins'],
                italian_word:['molto','più','meno'],
                english_phrase: ['The airport is very far away.','I like football but I prefer basket much more.','You need to talk less in the class.'],
                spanish_phrase: ['El aeropuerto está muy lejos.','Me gusta el fútbol, pero el baloncesto me gusta más.','Hay que hablar menos en clase.'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['L\'aeroporto è molto lontano.','Mi piace il calcio, ma il basket mi piace di più.','Si deve parlare meno in classe.']
            },
        ]
    }
}