module.exports =
{
    CONTENT:
    {
        CATEGORIES_INFO:
        [
            {
                english_title: 'EXISTENTIAL NOTIONS',
                spanish_title: 'NOCIONES EXISTENCIALES',
                german_title: 'NOCIONES EXISTENCIALES',
                french_title: 'NOCIONES EXISTENCIALES',
                italian_title: 'NOCIONES EXISTENCIALES',
                english_sub: ['Existence, lack of existence','Presence, absence','General quality','Event','Certainty, uncertainty'],
                spanish_sub: ['Existencia, inexistencia','Presencia, ausencia','Cualidad general','Acontecimiento','Certeza, incertidumbre'],
                german_sub: ['Existencia, inexistencia','Presencia, ausencia','Cualidad general','Acontecimiento','Certeza, incertidumbre'],
                french_sub: ['Existencia, inexistencia','Presencia, ausencia','Cualidad general','Acontecimiento','Certeza, incertidumbre'],
                italian_sub: ['Existencia, inexistencia','Presencia, ausencia','Cualidad general','Acontecimiento','Certeza, incertidumbre']
            },
            {
                english_title: 'QUANTITATIVE',
                spanish_title: 'NOCIONES CUANTITATIVAS',
                german_title: 'NOCIONES CUANTITATIVAS',
                french_title: 'NOCIONES CUANTITATIVAS',
                italian_title: 'NOCIONES CUANTITATIVAS',
                english_sub: ['Numerical quantity','Cardinal numbers','Ordinal numbers','Event','Relative quantity','Degree'],
                spanish_sub: ['Cantidad numérica','Números cardinales','Números ordinales','Cantidad relativa','Grado'],
                german_sub: ['Cantidad numérica','Números cardinales','Números ordinales','Cantidad relativa','Grado'],
                french_sub: ['Cantidad numérica','Números cardinales','Números ordinales','Cantidad relativa','Grado'],
                italian_sub: ['Cantidad numérica','Números cardinales','Números ordinales','Cantidad relativa','Grado']
            },
        ],
        EXISTENTIAL_NOTIONS:
        [
            {
                english_title: 'Existence, lack of existence',
                spanish_title: 'Existencia, inexistencia',
                german_title: 'Existencia, inexistencia',
                french_title: 'Existencia, inexistencia',
                italian_title: 'Existencia, inexistencia',
                english_explanation: ['there is (not) / thre are (not)','to have got','to live'],
                spanish_explanation: ['(no) haber','tener','vivir'],
                german_explanation: ['(no) haber','tener','vivir'],
                french_explanation: ['(no) haber','tener','vivir'],
                italian_explanation: ['(no) haber','tener','vivir'],
                english_phrase: ['There are many museums in Madrid. ','My house hasn\'t got a terrace.','I live in Switzerland. '],
                spanish_phrase: ['En Madrid hay muchos museos','Mi casa no tiene terraza.','Vivo en Suiza.'],
                german_phrase: ['En Madrid hay muchos museos','Mi casa no tiene terraza.','Vivo en Suiza.'],
                french_phrase: ['En Madrid hay muchos museos','Mi casa no tiene terraza.','Vivo en Suiza.'],
                italian_phrase: ['En Madrid hay muchos museos','Mi casa no tiene terraza.','Vivo en Suiza.']
            },
            {
                english_title: 'Presence, absence',
                spanish_title: 'Presencia, ausencia',
                german_title: 'Presencia, ausencia',
                french_title: 'Presencia, ausencia',
                italian_title: 'Presencia, ausencia',
                english_explanation: [' there is / thre are','(not) to be','without','with'],
                spanish_explanation: ['haber','(no) estar','sin','con'],
                german_explanation: ['haber','(no) estar','sin','con'],
                french_explanation: ['haber','(no) estar','sin','con'],
                italian_explanation: ['haber','(no) estar','sin','con'],
                english_phrase: ['There are many students in the class.','X11X is at home. ','I like coffee without sugar.','I drink tea with milk.'],
                spanish_phrase: ['Hay muchos alumnos en clase.','X11X está en casa.','Me gusta el café sin azúcar.','Bebo té con leche.'],
                german_phrase: ['Hay muchos alumnos en clase.','X11X está en casa.','Me gusta el café sin azúcar.','Bebo té con leche.'],
                french_phrase: ['Hay muchos alumnos en clase.','X11X está en casa.','Me gusta el café sin azúcar.','Bebo té con leche.'],
                italian_phrase: ['Hay muchos alumnos en clase.','X11X está en casa.','Me gusta el café sin azúcar.','Bebo té con leche.']
            },
            {
                english_title: 'General quality',
                spanish_title: 'Cualidad general',
                german_title: 'Cualidad general',
                french_title: 'Cualidad general',
                italian_title: 'Cualidad general',
                english_explanation: ['to be'],
                spanish_explanation: ['ser'],
                german_explanation: ['ser'],
                french_explanation: ['ser'],
                italian_explanation: ['ser'],
                english_phrase: ['The Spanish lesson is funny.'],
                spanish_phrase: ['La clase de español es divertida.'],
                german_phrase: ['La clase de español es divertida.'],
                french_phrase: ['La clase de español es divertida.'],
                italian_phrase: ['La clase de español es divertida.']
            },
            {
                english_title: 'Event',
                spanish_title: 'Acontecimiento',
                german_title: 'Acontecimiento',
                french_title: 'Acontecimiento',
                italian_title: 'Acontecimiento',
                english_explanation: ['to be'],
                spanish_explanation: ['ser'],
                german_explanation: ['ser'],
                french_explanation: ['ser'],
                italian_explanation: ['ser'],
                english_phrase: ['The party is tomorrow.'],
                spanish_phrase: ['La fiesta es mañana.'],
                german_phrase: ['La fiesta es mañana.'],
                french_phrase: ['La fiesta es mañana.'],
                italian_phrase: ['La fiesta es mañana.']
            },
            {
                english_title: 'Certainty, uncertainty',
                spanish_title: 'Certeza, incertidumbre',
                german_title: 'Certeza, incertidumbre',
                french_title: 'Certeza, incertidumbre',
                italian_title: 'Certeza, incertidumbre',
                english_explanation: ['maybe','perhaps/maybe'],
                spanish_explanation: ['ser possbile','quizá(s)'],
                german_explanation: ['ser possbile','quizá(s)'],
                french_explanation: ['ser possbile','quizá(s)'],
                italian_explanation: ['ser possbile','quizá(s)'],
                english_phrase: ['Are you coming to the cinema? Maybe. ','Are you going out tonight? Perhaps. '],
                spanish_phrase: ['Vienes al cine? Es posible. ','Sales esta noche? Quizás. '],
                german_phrase: ['Vienes al cine? Es posible. ','Sales esta noche? Quizás. '],
                french_phrase: ['Vienes al cine? Es posible. ','Sales esta noche? Quizás. '],
                italian_phrase: ['Vienes al cine? Es posible. ','Sales esta noche? Quizás. ']
            },
        ],
        QUANTITATIVE:
        [
            {
                english_title: 'Numerical quantity',
                spanish_title: 'Cantidad numérica',
                german_title: 'Cantidad numérica',
                french_title: 'Cantidad numérica',
                italian_title: 'Cantidad numérica',
                english_explanation:['number'],
                spanish_explanation:['numero'],
                german_explanation:['numero'],
                french_explanation:['numero'],
                italian_explanation:['numero'],
                english_phrase: ['They learn the numbers from 1 to 10'],
                spanish_phrase: ['Aprenden los números del 1 al 10.'],
                german_phrase: ['Aprenden los números del 1 al 10.'],
                french_phrase: ['Aprenden los números del 1 al 10.'],
                italian_phrase: ['Aprenden los números del 1 al 10.']
            },
            {
                english_title: 'Cardinal numbers',
                spanish_title: 'Números cardinales',
                german_title: 'Números cardinales',
                french_title: 'Números cardinales',
                italian_title: 'Números cardinales',
                english_explanation:['one','two','three','four'],
                spanish_explanation:['uno','dos','tres','cuatro'],
                german_explanation:['uno','dos','tres','cuatro'],
                french_explanation:['uno','dos','tres','cuatro'],
                italian_explanation:['uno','dos','tres','cuatro'],
                english_phrase: ['How many pencils do you want to buy? One.','I have two brothers.','My father has three children.','My house has four rooms.'],
                spanish_phrase: ['Cuántos lápices compras? Uno.','Tengo dos hermanos.','Mi padre tiene tres hijos.','Mi casa tiene cuatro habitaciones.'],
                german_phrase: ['Cuántos lápices compras? Uno.','Tengo dos hermanos.','Mi padre tiene tres hijos.','Mi casa tiene cuatro habitaciones.'],
                french_phrase: ['Cuántos lápices compras? Uno.','Tengo dos hermanos.','Mi padre tiene tres hijos.','Mi casa tiene cuatro habitaciones.'],
                italian_phrase: ['Cuántos lápices compras? Uno.','Tengo dos hermanos.','Mi padre tiene tres hijos.','Mi casa tiene cuatro habitaciones.']
            },
            {
                english_title: 'Ordinal numbers',
                spanish_title: 'Números ordinales',
                german_title: 'Números ordinales',
                french_title: 'Números ordinales',
                italian_title: 'Números ordinales',
                english_explanation:['first','second','third'],
                spanish_explanation:['primero','segundo','tercero'],
                german_explanation:['primero','segundo','tercero'],
                french_explanation:['primero','segundo','tercero'],
                italian_explanation:['primero','segundo','tercero'],
                english_phrase: ['Which floor do you live in? In the first floor.','Her house is in the second street.','He is the third of the list. '],
                spanish_phrase: ['En qué piso vives? En el primero.','Su casa está en la segunda calle.','Está el tercero en la lista.'],
                german_phrase: ['En qué piso vives? En el primero.','Su casa está en la segunda calle.','Está el tercero en la lista.'],
                french_phrase: ['En qué piso vives? En el primero.','Su casa está en la segunda calle.','Está el tercero en la lista.'],
                italian_phrase: ['En qué piso vives? En el primero.','Su casa está en la segunda calle.','Está el tercero en la lista.']
            },
            {
                english_title: 'Relative quantity',
                spanish_title: 'Cantidad relativa',
                german_title: 'Cantidad relativa',
                french_title: 'Cantidad relativa',
                italian_title: 'Cantidad relativa',
                english_explanation:['people','price','more'],
                spanish_explanation:['gente','precio','más'],
                german_explanation:['gente','precio','más'],
                french_explanation:['gente','precio','más'],
                italian_explanation:['gente','precio','más'],
                english_phrase: ['There are many people in the museum','How much is this handbag? I can\'t see the price.','Would you like more coffee?'],
                spanish_phrase: ['Hay mucha gente en el museo.','Qué precio tiene este bolso? ','Quieres más café?'],
                german_phrase: ['Hay mucha gente en el museo.','Qué precio tiene este bolso? ','Quieres más café?'],
                french_phrase: ['Hay mucha gente en el museo.','Qué precio tiene este bolso? ','Quieres más café?'],
                italian_phrase: ['Hay mucha gente en el museo.','Qué precio tiene este bolso? ','Quieres más café?'],
            },
            {
                english_title: 'Degree',
                spanish_title: 'Grado',
                german_title: 'Grado',
                french_title: 'Grado',
                italian_title: 'Grado',
                english_explanation:['very','much more','less'],
                spanish_explanation:['muy','más','menos'],
                german_explanation:['muy','más','menos'],
                french_explanation:['muy','más','menos'],
                italian_explanation:['muy','más','menos'],
                english_phrase: ['The airport is very far away.','I like football but I prefer basket much more.','You need to talk less in the class.'],
                spanish_phrase: ['El aeropuerto está muy lejos.','Me gusta el fútbol, pero el baloncesto me gusta más.','Hay que hablar menos en clase.'],
                german_phrase: ['El aeropuerto está muy lejos.','Me gusta el fútbol, pero el baloncesto me gusta más.','Hay que hablar menos en clase.'],
                french_phrase: ['El aeropuerto está muy lejos.','Me gusta el fútbol, pero el baloncesto me gusta más.','Hay que hablar menos en clase.'],
                italian_phrase: ['El aeropuerto está muy lejos.','Me gusta el fútbol, pero el baloncesto me gusta más.','Hay que hablar menos en clase.']
            },
        ]
    }
}