module.exports =
{
    CONTENT:
    {
        CATEGORIES_INFO:
        [
            {
                english_title: '<lang xml:lang="en-US">EXISTENTIAL NOTIONS</lang>',
                spanish_title: '<lang xml:lang="es-ES">NOCIONES EXISTENCIALES</lang>',
                german_title: '<lang xml:lang="de-DE">existenzielle Begriffe</lang>',
                french_title: '<lang xml:lang="fr-FR">notions existentielles</lang>',
                italian_title: '<lang xml:lang="it-IT">Nozioni esistenziali</lang>',
                english_sub:    ['<lang xml:lang="en-US">Existence, inexistence</lang>',      '<lang xml:lang="en-US">Presence, absence</lang>',        '<lang xml:lang="en-US">General quality</lang>',      '<lang xml:lang="en-US">Event</lang>',            '<lang xml:lang="en-US">Certainty, uncertainty</lang>'],
                spanish_sub:    ['<lang xml:lang="es-ES">Existencia, inexistencia</lang>',    '<lang xml:lang="es-ES">Presencia, ausencia</lang>',      '<lang xml:lang="es-ES">Cualidad general</lang>',     '<lang xml:lang="es-ES">Acontecimiento</lang>',   '<lang xml:lang="es-ES">Certeza, incertidumbre</lang>'],
                german_sub:     ['<lang xml:lang="de-DE">Existenz, Nichtexistenz</lang>',     '<lang xml:lang="de-DE">Anwesenheit, Abwesenheit</lang>', '<lang xml:lang="de-DE">Allgemeine Qualität</lang>',  '<lang xml:lang="de-DE">Veranstaltung</lang>',    '<lang xml:lang="de-DE">Sicherheit, Unsicherheit</lang>'],
                french_sub:     ['<lang xml:lang="fr-FR">Existencia, inexistencia</lang>',    '<lang xml:lang="fr-FR">Présence absence</lang>',         '<lang xml:lang="fr-FR">Qualité générale</lang>',     '<lang xml:lang="fr-FR">événement</lang>',        '<lang xml:lang="fr-FR">Certitude, incertitude</lang>'],
                italian_sub:    ['<lang xml:lang="it-IT">Esistenza, inesistenza</lang>',      '<lang xml:lang="it-IT">Presenza, assenza</lang>',        '<lang xml:lang="it-IT">Qualità generale</lang>',     '<lang xml:lang="it-IT">Avvenimento</lang>',      '<lang xml:lang="it-IT">Certezza, incertezza</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">QUANTITATIVE</lang>',
                spanish_title: '<lang xml:lang="es-ES">NOCIONES CUANTITATIVAS</lang>',
                german_title: '<lang xml:lang="de-DE">quantitativ</lang>',
                french_title: '<lang xml:lang="fr-FR">QUANTITATIVE</lang>',
                italian_title: '<lang xml:lang="it-IT">NOZIONI QUANTITATIVE</lang>',
                english_sub:    ['<lang xml:lang="en-US">Numerical quantity</lang>', '<lang xml:lang="en-US">Cardinal numbers</lang>',     '<lang xml:lang="en-US">Ordinal numbers</lang>',      '<lang xml:lang="en-US">Relative quantity</lang>',    '<lang xml:lang="en-US">Degree</lang>',],
                spanish_sub:    ['<lang xml:lang="es-ES">Cantidad numérica</lang>',  '<lang xml:lang="es-ES">Números cardinales</lang>',   '<lang xml:lang="es-ES">Números ordinales</lang>',    '<lang xml:lang="es-ES">Cantidad relativa</lang>',    '<lang xml:lang="es-ES">Grado</lang>'],
                german_sub:     ['<lang xml:lang="de-DE">Numerische Menge</lang>',    '<lang xml:lang="de-DE">Kardinalzahlen</lang>',       '<lang xml:lang="de-DE">Ordnungszahlen</lang>',       '<lang xml:lang="de-DE">Relative Menge</lang>',       '<lang xml:lang="de-DE">Grad</lang>'],
                french_sub:     ['<lang xml:lang="fr-FR">Quantité numérique</lang>',  '<lang xml:lang="fr-FR">nombres cardinaux</lang>',    '<lang xml:lang="fr-FR">Nombres ordinaux</lang>',     '<lang xml:lang="fr-FR">Quantité relative</lang>',    '<lang xml:lang="fr-FR">Degré</lang>'],
                italian_sub:    ['<lang xml:lang="it-IT">Quantità numerica</lang>',  '<lang xml:lang="it-IT">Numeri cardinali</lang>',   '<lang xml:lang="it-IT">Numeri ordinali</lang>',    '<lang xml:lang="it-IT">Quantità relativa</lang>',     '<lang xml:lang="it-IT">Grado</lang>']
            },
        ],
        EXISTENTIAL_NOTIONS:
        [
            {
                english_title: '<lang xml:lang="en-US">Existence, lack of existence</lang>',
                spanish_title: '<lang xml:lang="es-ES">Existencia, inexistencia</lang>',
                german_title: '<lang xml:lang="de-DE">Existenz, Nichtexistenz</lang>',
                french_title: '<lang xml:lang="fr-FR">Existencia, inexistencia</lang>',
                italian_title: '<lang xml:lang="it-IT">Esistenza, inesistenza</lang>',
                english_word: ['<lang xml:lang="en-US">there is (not) / there are (not)</lang>','<lang xml:lang="en-US">to have got</lang>','<lang xml:lang="en-US">to live</lang>'],
                spanish_word: ['<lang xml:lang="es-ES">(no) haber</lang>','<lang xml:lang="es-ES">tener</lang>','<lang xml:lang="es-ES">vivir</lang>'],
                german_word: ['<lang xml:lang="de-DE">(kein […]) geben</lang>','<lang xml:lang="de-DE">haben</lang>','<lang xml:lang="de-DE">leben</lang>'],
                french_word: ['<lang xml:lang="fr-FR">(ne pas) avoir</lang>','<lang xml:lang="fr-FR">avoir</lang>','<lang xml:lang="fr-FR">vivre</lang>'],
                italian_word: ['<lang xml:lang="it-IT">(non) esserci</lang>','<lang xml:lang="it-IT">avere</lang>','<lang xml:lang="it-IT">vivere</lang>'],
                english_phrase: ['<lang xml:lang="en-US">There are many museums in Madrid. </lang>','<lang xml:lang="en-US">My house hasn\'t got a terrace.</lang>','<lang xml:lang="en-US">I live in Switzerland. </lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">En Madrid hay muchos museos</lang>','<lang xml:lang="es-ES">Mi casa no tiene terraza.</lang>','<lang xml:lang="es-ES">Vivo en Suiza.</lang>'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['<lang xml:lang="it-IT">A Madrid ci sono molti musei.</lang>','<lang xml:lang="it-IT">La mia casa non ha il terrazzo.</lang>','<lang xml:lang="it-IT">Vivo a Barcellona.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Presence, absence</lang>',
                spanish_title: '<lang xml:lang="es-ES">Presencia, ausencia</lang>',
                german_title: '<lang xml:lang="de-DE">Anwesenheit, Abwesenheit</lang>',
                french_title: '<lang xml:lang="fr-FR">Présence absence</lang>',
                italian_title: '<lang xml:lang="it-IT">Presenza, assenza</lang>',
                english_word: ['<lang xml:lang="en-US"> there is / thre are</lang>','<lang xml:lang="en-US">(not) to be</lang>','without</lang>','<lang xml:lang="en-US">with</lang>'],
                spanish_word: ['<lang xml:lang="es-ES">haber</lang>','<lang xml:lang="es-ES">(no) estar</lang>','<lang xml:lang="es-ES">sin</lang>','<lang xml:lang="es-ES">con</lang>'],
                german_word: ['','<lang xml:lang="de-DE">(nicht) sein, <lang xml:lang="de-DE">(sich) befinden</lang>','<lang xml:lang="de-DE">ohne</lang>','mit</lang>'],
                french_word: ['<lang xml:lang="fr-FR">avoir</lang>','<lang xml:lang="fr-FR">(ne pas) être</lang>','<lang xml:lang="fr-FR">sans</lang>','<lang xml:lang="fr-FR">avec</lang>'],
                italian_word: ['<lang xml:lang="it-IT">esserci</lang>','<lang xml:lang="it-IT">(non) essere</lang>','<lang xml:lang="it-IT">senza</lang>','con</lang>'],
                english_phrase: ['<lang xml:lang="en-US">There are many students in the class.</lang>','<lang xml:lang="en-US">Peter is at home. </lang>','I like coffee without sugar.</lang>','<lang xml:lang="en-US">I drink tea with milk.</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">Hay muchos alumnos en clase.</lang>','<lang xml:lang="es-ES">Pedro está en casa.</lang>','<lang xml:lang="es-ES">Me gusta el café sin azúcar.</lang>','<lang xml:lang="es-ES">Bebo té con leche.</lang>'],
                german_phrase: ['','','',''],
                french_phrase: ['','','',''],
                italian_phrase: ['<lang xml:lang="it-IT">Ci sono molti alunni in classe.</lang>','<lang xml:lang="it-IT">Pietro è a casa.</lang>','<lang xml:lang="it-IT">Mi piace il caffè senza zucchero.</lang>','<lang xml:lang="it-IT">Bevo tè con latte.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">General quality</lang>',
                spanish_title: '<lang xml:lang="es-ES">Cualidad general</lang>',
                german_title: '<lang xml:lang="de-DE">Allgemeine Qualität</lang>',
                french_title: '<lang xml:lang="fr-FR">Qualité générale</lang>',
                italian_title: '<lang xml:lang="it-IT">Qualità generale</lang>',
                english_word: ['<lang xml:lang="en-US">to b</lang>e'],
                spanish_word: ['<lang xml:lang="es-ES">ser</lang>'],
                german_word: ['<lang xml:lang="de-DE">sein</lang>'],
                french_word: ['<lang xml:lang="fr-FR">être</lang>'],
                italian_word: ['<lang xml:lang="it-IT">essere</lang>'],
                english_phrase: ['<lang xml:lang="en-US">The Spanish lesson is funny.</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">La clase de español es divertida.</lang>'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['<lang xml:lang="it-IT">La lezione di spagnolo è divertente.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Event</lang>',
                spanish_title: '<lang xml:lang="es-ES">Acontecimiento</lang>',
                german_title: '<lang xml:lang="de-DE">Veranstaltung</lang>',
                french_title: '<lang xml:lang="fr-FR">événement</lang>',
                italian_title: '<lang xml:lang="it-IT">Avvenimento</lang>',
                english_word: ['<lang xml:lang="en-US">to be</lang>'],
                spanish_word: ['<lang xml:lang="es-ES">ser</lang>'],
                german_word: ['<lang xml:lang="de-DE">sein, stattfinden</lang>'],
                french_word: ['<lang xml:lang="fr-FR">avoir lieu</lang>'],
                italian_word: ['<lang xml:lang="it-IT">essere</lang>'],
                english_phrase: ['<lang xml:lang="en-US">The party is tomorrow.</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">La fiesta es mañana.</lang>'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['<lang xml:lang="it-IT">La festa è domani.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Certainty, uncertainty</lang>',
                spanish_title: '<lang xml:lang="es-ES">Certeza, incertidumbre</lang>',
                german_title: '<lang xml:lang="de-DE">Sicherheit, Unsicherheit</lang>',
                french_title: '<lang xml:lang="fr-FR">Certitude, incertitude</lang>',
                italian_title: '<lang xml:lang="it-IT">Certezza, incertezza</lang>',
                english_word: ['<lang xml:lang="en-US">maybe</lang>','<lang xml:lang="en-US">perhaps/maybe</lang>'],
                spanish_word: ['<lang xml:lang="es-ES">ser possbile</lang>','<lang xml:lang="es-ES">quizá(s)</lang>'],
                german_word: ['<lang xml:lang="de-DE">möglich sein</lang>','<lang xml:lang="de-DE">vielleicht</lang>'],
                french_word: ['<lang xml:lang="fr-FR">être possible</lang>','<lang xml:lang="fr-FR">peut-être</lang>'],
                italian_word: ['<lang xml:lang="it-IT">essere possibile</lang>','<lang xml:lang="it-IT">quizá(s)</lang>'],
                english_phrase: ['<lang xml:lang="en-US">Are you coming to the cinema? Maybe. </lang>','<lang xml:lang="en-US">Are you going out tonight? Perhaps. </lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">Vienes al cine? Es posible. </lang>','<lang xml:lang="es-ES">Sales esta noche? Quizás. </lang>'],
                german_phrase: ['',''],
                french_phrase: ['',''],
                italian_phrase: ['<lang xml:lang="it-IT">Vieni al cinema? È possibile.</lang>','<lang xml:lang="it-IT">Esci questa sera? Forse.</lang>']
            },
        ],
        QUANTITATIVE:
        [
            {
                english_title: '<lang xml:lang="en-US">Numerical quantity</lang>',
                spanish_title: '<lang xml:lang="es-ES">Cantidad numérica</lang>',
                german_title: '<lang xml:lang="de-DE">Numerische Menge</lang>',
                french_title: '<lang xml:lang="fr-FR">Quantité numérique</lang>',
                italian_title: '<lang xml:lang="it-IT">Quantità numerica</lang>',
                english_word:['<lang xml:lang="en-US">number</lang>'],
                spanish_word:['<lang xml:lang="es-ES">numero</lang>'],
                german_word:['<lang xml:lang="de-DE">Zahl</lang>'],
                french_word:['<lang xml:lang="fr-FR">nombre</lang>'],
                italian_word:['<lang xml:lang="it-IT">numero</lang>'],
                english_phrase: ['<lang xml:lang="en-US">They learn the numbers from 1 to 10</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">Aprenden los números del 1 al 10.</lang>'],
                german_phrase: [''],
                french_phrase: [''],
                italian_phrase: ['<lang xml:lang="it-IT">Imparano i numeri da 1 a 10.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Cardinal numbers</lang>',
                spanish_title: '<lang xml:lang="es-ES">Números cardinales</lang>',
                german_title: '<lang xml:lang="de-DE">Kardinalzahlen</lang>',
                french_title: '<lang xml:lang="fr-FR">nombres cardinaux</lang>',
                italian_title: '<lang xml:lang="it-IT">Numeri cardinali</lang>',
                english_word:['<lang xml:lang="en-US">one</lang>','<lang xml:lang="en-US">two</lang>','<lang xml:lang="en-US">three</lang>','<lang xml:lang="en-US">four</lang>'],
                spanish_word:['<lang xml:lang="es-ES">uno</lang>','<lang xml:lang="es-ES">dos</lang>','<lang xml:lang="es-ES">tres</lang>','<lang xml:lang="es-ES">cuatro</lang>'],
                german_word:['<lang xml:lang="de-DE">eins</lang>','<lang xml:lang="de-DE">zwei</lang>','<lang xml:lang="de-DE">drei</lang>','<lang xml:lang="de-DE">vier</lang>'],
                french_word:['<lang xml:lang="fr-FR">un</lang>','<lang xml:lang="fr-FR">deux</lang>','<lang xml:lang="fr-FR">trois</lang>','<lang xml:lang="fr-FR">quatre</lang>'],
                italian_word:['<lang xml:lang="it-IT">uno</lang>','<lang xml:lang="it-IT">due</lang>','<lang xml:lang="it-IT">tre</lang>','<lang xml:lang="it-IT">quattro</lang>'],
                english_phrase: ['<lang xml:lang="en-US">How many pencils do you want to buy? One.</lang>','<lang xml:lang="en-US">I have two brothers.</lang>','My father has three children.</lang>','<lang xml:lang="en-US">My house has four rooms.</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">Cuántos lápices compras? Uno.</lang>','<lang xml:lang="es-ES">Tengo dos hermanos.</lang>','<lang xml:lang="es-ES">Mi padre tiene tres hijos.</lang>','<lang xml:lang="es-ES">Mi casa tiene cuatro habitaciones.</lang>'],
                german_phrase: ['','','',''],
                french_phrase: ['','','',''],
                italian_phrase: ['<lang xml:lang="it-IT">Quante matite compri? Una.</lang>','<lang xml:lang="it-IT">Ho due fratelli</lang>','<lang xml:lang="it-IT">Mio padre ha tre figli.</lang>','<lang xml:lang="it-IT">La mia casa ha quattro stanze.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Ordinal numbers</lang>',
                spanish_title: '<lang xml:lang="es-ES">Números ordinales</lang>',
                german_title: '<lang xml:lang="de-DE">Ordinalzahlen</lang>',
                french_title: '<lang xml:lang="fr-FR">Nombres ordinaux</lang>',
                italian_title: '<lang xml:lang="it-IT">Numeri ordinali</lang>',
                english_word:['<lang xml:lang="en-US">first</lang>','<lang xml:lang="en-US">second</lang>','<lang xml:lang="en-US">third</lang>'],
                spanish_word:['<lang xml:lang="es-ES">primero</lang>','<lang xml:lang="es-ES">segundo</lang>','<lang xml:lang="es-ES">tercero</lang>'],
                german_word:['<lang xml:lang="de-DE">Erstens, erster, erste, erstes</lang>','<lang xml:lang="de-DE">zweiter, zweite, zweites</lang>','<lang xml:lang="de-DE">dritter, dritte</lang>'],
                french_word:['<lang xml:lang="fr-FR">premier</lang>','<lang xml:lang="fr-FR">deuxième</lang>','<lang xml:lang="fr-FR">troisième</lang>'],
                italian_word:['<lang xml:lang="it-IT">primo</lang>','<lang xml:lang="it-IT">secondo</lang>','<lang xml:lang="it-IT">terzo</lang>'],
                english_phrase: ['<lang xml:lang="en-US">Which floor do you live in? In the first floor.</lang>','<lang xml:lang="en-US">Her house is in the second street.</lang>','<lang xml:lang="en-US">He is the third of the list. </lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">En qué piso vives? En el primero.','<lang xml:lang="es-ES">Su casa está en la segunda calle.','<lang xml:lang="es-ES">Está el tercero en la lista.'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['<lang xml:lang="it-IT">A che piano vivi? Al primo</lang>','<lang xml:lang="it-IT">La sua casa si trova nella seconda strada.</lang>','<lang xml:lang="it-IT">È il terzo della lista.</lang>']
            },
            {
                english_title: '<lang xml:lang="en-US">Relative quantity</lang>',
                spanish_title: '<lang xml:lang="es-ES">Cantidad relativa</lang>',
                german_title: '<lang xml:lang="de-DE">Relative Menge</lang>',
                french_title: '<lang xml:lang="fr-FR">Quantité relative</lang>',
                italian_title: '<lang xml:lang="it-IT">Quantità relativa</lang>',
                english_word:['<lang xml:lang="en-US">people</lang>','<lang xml:lang="en-US">price</lang>','<lang xml:lang="en-US">more</lang>'],
                spanish_word:['<lang xml:lang="es-ES">gente</lang>','<lang xml:lang="es-ES">precio</lang>','<lang xml:lang="es-ES">más</lang>'],
                german_word:['<lang xml:lang="de-DE">Menschen</lang>','<lang xml:lang="de-DE">Preis</lang>','<lang xml:lang="de-DE">mehr</lang>'],
                french_word:['<lang xml:lang="fr-FR">gens</lang>','<lang xml:lang="fr-FR">prix</lang>','<lang xml:lang="fr-FR">plus</lang>'],
                italian_word:['<lang xml:lang="it-IT">gente</lang>','<lang xml:lang="it-IT">prezzo</lang>','<lang xml:lang="it-IT">più</lang>'],
                english_phrase: ['<lang xml:lang="en-US">There are many people in the museum</lang>','<lang xml:lang="en-US">How much is this handbag? I can\'t see the price.</lang>','<lang xml:lang="en-US">Would you like more coffee?</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">Hay mucha gente en el museo.</lang>','<lang xml:lang="es-ES">Qué precio tiene este bolso?</lang> ','<lang xml:lang="es-ES">Quieres más café?</lang>'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['<lang xml:lang="it-IT">C\'è molta gente nel museo.</lang>','<lang xml:lang="it-IT">Che prezzo ha questa borsa?</lang>','<lang xml:lang="it-IT"> Mi piace con più latte.</lang>'],
            },
            {
                english_title: '<lang xml:lang="en-US">Degree</lang>',
                spanish_title: '<lang xml:lang="es-ES">Grado</lang>',
                german_title: '<lang xml:lang="de-DE">Grad</lang>',
                french_title: '<lang xml:lang="fr-FR">Degré</lang>',
                italian_title: '<lang xml:lang="it-IT">Grado</lang>',
                english_word:['<lang xml:lang="en-US">very</lang>','<lang xml:lang="en-US">much more</lang>','<lang xml:lang="en-US">less</lang>'],
                spanish_word:['<lang xml:lang="es-ES">muy</lang>','<lang xml:lang="es-ES">más</lang>','<lang xml:lang="es-ES">menos</lang>'],
                german_word:['<lang xml:lang="de-DE">sehr</lang>','<lang xml:lang="de-DE">mehr, lieber</lang>','<lang xml:lang="de-DE">wenig</lang>'],
                french_word:['<lang xml:lang="fr-FR">très</lang>','<lang xml:lang="fr-FR">plus</lang>','<lang xml:lang="fr-FR">moins</lang>'],
                italian_word:['<lang xml:lang="it-IT">molto</lang>','<lang xml:lang="it-IT">più</lang>','<lang xml:lang="it-IT">meno</lang>'],
                english_phrase: ['<lang xml:lang="en-US">The airport is very far away.</lang>','<lang xml:lang="en-US">I like football but I prefer basket much more.</lang>','<lang xml:lang="en-US">You need to talk less in the class.</lang>'],
                spanish_phrase: ['<lang xml:lang="es-ES">El aeropuerto está muy lejos.</lang>','<lang xml:lang="es-ES">Me gusta el fútbol, pero el baloncesto me gusta más.</lang>','<lang xml:lang="es-ES">Hay que hablar menos en clase.</lang>'],
                german_phrase: ['','',''],
                french_phrase: ['','',''],
                italian_phrase: ['<lang xml:lang="it-IT">L\'aeroporto è molto lontano.</lang>','<lang xml:lang="it-IT">Mi piace il calcio, ma il basket mi piace di più.</lang>','<lang xml:lang="it-IT">Si deve parlare meno in classe.</lang>']
            },
        ]
    }
}